### ISSUE TITLE
Use a single replication controller and service

### ISSUE THREAD

**Issue by tim-smart** [cvallance/mongo-k8s-sidecar#13]
Currently it looks like you create a service for every replica?

What would we need to do to make the replica model (or something similar):

```svc/mongo -> rc/mongo -> lots of mongo pods```

It has been mentions, but PetSets could be a good fit for mongo clusters.

**Comment by cvallance** [comment]
PetSets are the perfect fit for mongo clusters in k8s. They weren't available when this project was first created so none of the examples use them.

This project is still fully compatible with PetSets because they still create Pods which in turn have labels, this is all the project requires to setup a ReplicaSet.

**Comment by tim-smart** [comment]
Ah yes, I see how the label thing works now.

I guess the only issue with using one service per replica set is having a
nice way to get all the pod ips for the client connection. There are ways
around it I can see, but they add extra complexity which is annoying!

**Comment by cvallance** [comment]
Yeah, it is quite annoying but I found out the hard way that it's necessary in that when you connect to a replica set, you can't just connect via a service because this will just load balance you randomly to one machine... you need to have all the replica set members in the mongo connection string... hence the need for 1 service per pod.

PetSets definitely make it slightly easier.

I had created another project for nodejs which would query the kubernetes api to get a list of pods for some labels (like this project) and would create a mongo connection string based off the results... you can find it here: https://github.com/cvallance/mongo-k8s-connstr
